name: Build and Push Docker Image

on:
  release:
    types: [published]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional tag to use (leave empty for default tags)'
        required: false
        type: string

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' && inputs.tag == 'latest' }}
            type=semver,pattern={{version}},enable=${{ github.event_name == 'release' }}
            type=sha,format=short,enable=${{ github.event_name == 'push' }}
            type=raw,value=manual-${{ github.sha }},enable=${{ github.event_name == 'workflow_dispatch' && inputs.tag == '' }}
            ${{ github.event_name == 'workflow_dispatch' && inputs.tag != '' && format('type=raw,value={0}', inputs.tag) || '' }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 